import { regionMetaSchema, type RegionMeta } from './schema.ts';

export const regionMetas: RegionMeta[] = [
  { id: 'languages', title: 'Languages', label: 'Syntax is the road sign, not the road.', description: 'JavaScript, TypeScript, Python, SQL, and why agents made syntax less central but not irrelevant.', mapArea: { x: 8, y: 12, width: 20, height: 28 }, landmarkIds: ['javascript-typescript', 'python', 'html-css', 'types-and-contracts', 'runtimes-and-packages', 'reading-generated-code'] },
  { id: 'databases', title: 'Databases', label: 'Where app memory becomes product memory.', description: 'SQL, NoSQL, vector, graph, ORMs, and hosted-vs-self-hosted defaults.', mapArea: { x: 33, y: 10, width: 26, height: 34 }, landmarkIds: ['sql', 'nosql-document', 'vector', 'graph', 'orm-vs-raw-sql', 'hosted-vs-self-hosted-databases'] },
  { id: 'infra', title: 'Infra / Hosting', label: 'The deployment terrain under every working app.', description: 'Serverless, VPS, containers, edge, static CDN, and managed platforms.', mapArea: { x: 64, y: 16, width: 27, height: 30 }, landmarkIds: ['serverless-functions', 'vps-single-server', 'containers', 'edge-compute', 'static-cdn', 'managed-platforms'] },
  { id: 'ai-types', title: 'AI Types', label: 'Chat, agents, RAG, tools, evals, and model routing.', description: 'The difference between a model call, an agent, a workflow, and a product feature.', mapArea: { x: 11, y: 50, width: 26, height: 30 }, landmarkIds: ['model-call-vs-agent', 'retrieval-augmented-generation', 'tool-use', 'workflows-vs-agents', 'ai-evals', 'model-selection-routing'] },
  { id: 'pm-tools', title: 'PM Tools', label: 'Linear, issues, specs, and the work graph agents read.', description: 'Project management as machine-readable product memory, not just human planning.', mapArea: { x: 42, y: 52, width: 19, height: 25 }, landmarkIds: ['issues-as-specs', 'prd-lite', 'vertical-slices', 'dependencies-and-work-graphs', 'decision-logs', 'backlog-vs-now'] },
  { id: 'git', title: 'Git', label: 'The time machine every serious builder eventually needs.', description: 'Branches, commits, PRs, reviews, and why agents need clean version control.', mapArea: { x: 66, y: 55, width: 21, height: 20 }, landmarkIds: ['commits-as-checkpoints', 'branches-as-isolation', 'pull-requests-and-review', 'merge-conflicts', 'working-tree-hygiene', 'revert-and-recovery'] },
  { id: 'security', title: 'Security', label: 'Secrets, permissions, trust boundaries, and blast radius.', description: 'The minimum safety map for apps built with fast-moving AI assistance.', mapArea: { x: 20, y: 82, width: 26, height: 13 }, landmarkIds: ['secrets-and-environment', 'authentication-vs-authorization', 'trust-boundaries', 'input-validation-and-injection', 'dependency-supply-chain', 'least-privilege-blast-radius'] },
  { id: 'design', title: 'Design Systems', label: 'The layer between a working app and a believable app.', description: 'Tokens, components, patterns, accessibility, and professional visual consistency.', mapArea: { x: 53, y: 82, width: 28, height: 13 }, landmarkIds: ['design-tokens', 'component-libraries', 'layout-and-spacing-rhythm', 'typography-and-hierarchy', 'accessibility-floor', 'consistency-vs-novelty'] }
].map((region) => regionMetaSchema.parse(region));
